### ISSUE TITLE
Tape positions  crashes when doing something stupid 

### ISSUE THREAD

**Issue by BuildItAnyway** [jkuusama/LitePlacer-DEV#20] opened 2015-10-29 21:40 UTC
See:
http://i.imgur.com/DXjpD3L.png

I accidentally loaded a custom tapes file into tape potions. Now it crashes whenever you look at it.

Now I know what I did was not normal behavior but the exception should be handled.

**Comment by jkuusama** [comment] 2019-08-07 13:24
Old bug report, that I can't reproduce in the current version. Fixed by side-effect, I think,

**Closed as completed** 2019-08-07 13:25 UTC
